#!/usr/bin/env ts-node
/**
 * Bundle builder for network interceptor libraries
 *
 * Creates a standalone bundle of heavy dependencies:
 * - protobufjs (~200KB minified)
 * - pako (~45KB minified)
 *
 * This bundle is loaded once via page.addInitScript({ path })
 * Browser logic remains inline (receives PROTO_SCHEMA dynamically)
 *
 * Benefits:
 * - Reduces inline script from ~250KB to ~30KB
 * - Single file load vs massive string concatenation
 * - Browser logic still dynamic (no rebuild needed for schema changes)
 */

import * as fs from "node:fs"
import * as path from "node:path"

function buildLibrariesBundle() {
  console.log("🔨 Building network-interceptor libraries bundle...")

  try {
    // Read protobufjs
    console.log("  📦 Loading protobufjs (~200KB)...")
    const protobufPath = require.resolve("protobufjs/dist/protobuf.min.js")
    const protobufCode = fs.readFileSync(protobufPath, "utf8")

    // Read pako
    console.log("  📦 Loading pako (~45KB)...")
    const pakoPath = require.resolve("pako/dist/pako.min.js")
    const pakoCode = fs.readFileSync(pakoPath, "utf8")

    // Create libraries bundle
    const bundle = `// ===== NETWORK INTERCEPTOR LIBRARIES BUNDLE =====
// Auto-generated by build-bundle.ts
// Contains: protobufjs + pako
// Browser logic is loaded separately (inline) to remain dynamic

(function() {
    "use strict";

    try {
        console.log("[NetworkInterceptor] Loading libraries bundle...");

        // ===== PROTOBUFJS (~200KB) =====
        ${protobufCode}

        // ===== PAKO (~45KB) =====
        ${pakoCode}

        // ===== SETUP GLOBALS =====
        if (typeof window !== "undefined") {
            window.protobuf = window.protobuf || window.protobufjs;
            // pako is already set by the library itself
        }

        if (!window.protobuf || !window.pako) {
            console.error("[NetworkInterceptor] Failed to load dependencies");
            return;
        }

        console.log("[NetworkInterceptor] Libraries loaded successfully");
        console.log("[NetworkInterceptor] protobuf:", typeof window.protobuf);
        console.log("[NetworkInterceptor] pako:", typeof window.pako);

    } catch (e) {
        console.error("[NetworkInterceptor] Libraries bundle error:", e);
    }
})();
`

    // Write bundle
    const outputDir = path.resolve(__dirname, "bundle")
    fs.mkdirSync(outputDir, { recursive: true })
    const outputPath = path.join(outputDir, "network-interceptor-libs.bundle.js")
    fs.writeFileSync(outputPath, bundle, "utf8")

    const stats = fs.statSync(outputPath)
    const sizeKB = (stats.size / 1024).toFixed(1)

    console.log(`✅ Libraries bundle created: ${outputPath}`)
    console.log(`   Size: ${sizeKB} KB`)
    console.log(`   ~${(stats.size / (1024 * 1024)).toFixed(2)} MB`)

  } catch (error) {
    console.error("❌ Bundle build failed:", error)
    process.exit(1)
  }
}

// Run if called directly
if (require.main === module) {
  buildLibrariesBundle()
}

export { buildLibrariesBundle }
