name: Test Suite

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
  push:
    branches: [main]

jobs:
  test-recording-server:
    name: Test Recording Server
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.16, 16.x, 18.x]

    defaults:
      run:
        working-directory: ./recording_server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./recording_server/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript build
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Run test coverage
        run: npm run test:coverage

      - name: Upload coverage reports
        if: matrix.node-version == '16.x'
        uses: codecov/codecov-action@v3
        with:
          directory: ./recording_server/coverage
          fail_ci_if_error: false

  test-chrome-extension:
    name: Test Chrome Extension
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.16, 16.x, 18.x]

    defaults:
      run:
        working-directory: ./recording_server/chrome_extension

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./recording_server/chrome_extension/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Check formatting
        run: npm run format -- --check

  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: ./recording_server/package-lock.json

      - name: Install recording server dependencies
        run: npm ci
        working-directory: ./recording_server

      - name: Install chrome extension dependencies
        run: npm ci
        working-directory: ./recording_server/chrome_extension

      - name: Check recording server formatting
        run: npm run format -- --check
        working-directory: ./recording_server

      - name: Check chrome extension formatting
        run: npm run format -- --check
        working-directory: ./recording_server/chrome_extension

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t meet-teams-bot:test .

      - name: Test Docker image
        run: docker run --rm meet-teams-bot:test --help || true
